### ISSUE TITLE
[BUG] Linting not working properly after 1.0.5 in CDN

### ISSUE THREAD

**Issue by p4bloch** [OlegIlyenko/graphiql-workspace#26]
First of all, thank you all contributors for this valuable tool. I'd like to report a bug that I encountered, which was introduced in version `1.0.5`. See gif below.

![1 0 5-bug](https://user-images.githubusercontent.com/3620912/31076983-0d454316-a77d-11e7-97b2-8af9c4b5024a.gif)

The problem is that when I use `1.0.5` from the CDN and try to get linting on the fields of an operation, I get the following error.

```
Uncaught Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
    at invariant (graphiql-workspace.js:27632)
    at validate (graphiql-workspace.js:38890)
    at validateWithCustomRules (graphiql-workspace.js:40136)
    at getDiagnostics (graphiql-workspace.js:25019)
    at graphiql-workspace.js:3322
    at startLinting (graphiql-workspace.js:6663)
    at graphiql-workspace.js:6706
```
I could not trace any of the calls of that stack to the actual codebase here, so I'm guessing this has to do with a graphql/graphiql dependency in the bundled files.

Using `1.0.4` against the same schema, with the same query, works just fine.

cc @tlvenn - your commits were the main change from 4 to 5 so maybe you have an idea :)

**Comment by OlegIlyenko** [comment]
Just published https://github.com/OlegIlyenko/graphiql-workspace/releases/tag/v1.1.1 I think it should fix the issue. *Important:* in my tests, only this combination of dependency version actually  worked:

```js
"dependencies": {
  // ...
  "graphiql-workspace": "1.1.1",
  "graphiql": "^0.11.5",
  "graphql": "^0.10.0"
},
```

I removed the dependency on `graphiql-subscriptions-fetcher` since the project is quite outdated and it does not look like it is maintained. Moreover, it exports just one small function which I just copy/pasted in this project.

The dependency (especially transitive dependency) version management in npm/yarn is quite a mess. graphql-js is one of the few libs that actually makes an explicit check for different versions. If there is a small mismatch in transitive versions, it will throw these errors :(

All that said, I am very very far from being an expert in npm dependency management. I would really appreciate a review from somebody who is more experienced in this area. In particular this change: https://github.com/OlegIlyenko/graphiql-workspace/commit/62589799ee30f170b42bec54167f3401ac8fb9f7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by tlvenn** [comment]
Thanks @OlegIlyenko for taking a stab at this.

Looking at the change you mentioned, I am a bit surprised that the peer dependency on graphql is targeting 0.11.x while you are saying above that you actually need graphql 0.10.X.

Wouldn't this lead to npm / yarn complaining that the peer dependency is not meet ?

**Comment by p4bloch** [comment]
I tried `1.1.1` but it did not fix the issue for me, the same error is thrown with the same action. These are the dependencies I'm using

```html
<link rel="stylesheet" media="screen" href="//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
<link rel="stylesheet" media="screen" href="//cdnjs.cloudflare.com/ajax/libs/graphiql/0.9.3/graphiql.min.css">
<link rel="stylesheet" media="screen" href="//cdn.jsdelivr.net/npm/graphiql-workspace@1.1.1/graphiql-workspace.css">

<script src="//cdn.jsdelivr.net/react/15.4.2/react.min.js"></script>
<script src="//cdn.jsdelivr.net/react/15.4.2/react-dom.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/graphiql-workspace@1.1.1/graphiql-workspace.min.js"></script>
```

**Comment by tlvenn** [comment]
Hi @p4bloch , this does not seem to match the working combination of dependencies that @OlegIlyenko outlined above (`graphiql@0.9.3` vs `graphiql@0.11.5`)

**Comment by p4bloch** [comment]
Hey @tlvenn! Actually that's just the css, the graphiql version is included in the minified dist file. Anyway, I tried changing the CSS to match the bundled graphiql version but it did not change the outcome.

**Comment by tlvenn** [comment]
oups my bad... I will try to look into it soon as well.

**Comment by tlvenn** [comment]
Sorry it took so long to get back to this issue, I have submitted a PR to fix it for good.

**Comment by tlvenn** [comment]
@OlegIlyenko any chance you can merge my PR and cut a release please ? Thanks in advance.

Right now 1.1.2 is broken as it still bundles 2 versions of graphql.
